FROM debian:bookworm

ARG TARGETARCH
ARG VERSION

RUN apt-get -y update && apt-get install -y --no-install-recommends \
    apt-utils curl nano git cmake build-essential ninja-build ca-certificates\
	libwayland-client0 libwayland-server0 libglx-mesa0 mesa-utils-extra \
	libegl1 libgles2 libgles-dev libxcb-cursor0 \
	libfontconfig-dev libopengl-dev libpng-dev libfreetype-dev libxkbcommon-dev

COPY build-$VERSION/linux_$TARGETARCH/Qt6-$TARGETARCH.tar.xz /import/

RUN mkdir -p /opt/Qt6
RUN tar xvfp /import/Qt6-$TARGETARCH.tar.xz -C /opt/Qt6
RUN rm /import/Qt6-$TARGETARCH.tar.xz

RUN echo "/opt/Qt6/lib" >> /etc/ld.so.conf && ldconfig
ENV PATH="${PATH}:/opt/Qt6"
ENV QT_DIR="/opt/Qt6"
ENV QT_PLUGIN_PATH="/opt/Qt6/plugins"