FROM debian:bookworm

ARG TARGETARCH
ARG VERSION

RUN apt-get -y update && apt-get install -y --no-install-recommends \
    apt-utils curl nano git cmake build-essential ninja-build ca-certificates\
	libwayland-dev libgles-dev libglx-mesa0 mesa-utils-extra  \
	libopengl-dev libpng-dev libfontconfig1-dev libfreetype6-dev \
    libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev \
	libxrender-dev libxcb1-dev libxcb-cursor-dev \
    libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev \
	libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev \
    libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev \
	libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev \
	libxkbcommon-dev libxkbcommon-x11-dev

COPY build-$VERSION/Qt6-$TARGETARCH.tar.xz /import/

RUN mkdir -p /opt/Qt6
RUN tar xvfp /import/Qt6-$TARGETARCH.tar.xz -C /opt/Qt6
COPY build-$VERSION/Qt6-$TARGETARCH-config.summary /opt/Qt6/config.summary
RUN rm /import/Qt6-$TARGETARCH.tar.xz

RUN echo "/opt/Qt6/lib" >> /etc/ld.so.conf && ldconfig
ENV PATH="${PATH}:/opt/Qt6"
ENV QT_DIR="/opt/Qt6"
ENV QT_PLUGIN_PATH="/opt/Qt6/plugins"
# Set the default display server for Raspberry Pi. Use "wayland" if there is a need.
ENV QT_QPA_PLATFORM=eglfs

RUN apt-get -y autoremove \
	&& apt-get -y autoclean \
	&& apt-get -y clean \
	&& rm -rf /var/lib/apt/lists/*
