FROM debian:bookworm-slim as compile-base

ARG TARGETARCH
ARG VERSION

RUN apt-get -y update && apt-get install -y --no-install-recommends \
	apt-utils git cmake build-essential ninja-build curl ca-certificates \
	libwayland-dev \
	libopengl-dev \
	libgles-dev \
	libxcb-cursor-dev \
	libfontconfig-dev \
	libpng-dev \
	libfreetype-dev \
	libxkbcommon-dev \
	postgresql-common

# Add PostgreSQL repository and install dev lib
RUN install -d /usr/share/postgresql-common/pgdg && \
    curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc && \
    sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list' && \
    apt-get -y update && \
    apt-get install -y --no-install-recommends libpq-dev postgresql-server-dev-16



FROM compile-base AS compile

COPY build-$VERSION-slim/Qt6-$TARGETARCH.tar.xz /import/

RUN mkdir -p /opt/Qt6
RUN tar xvfp /import/Qt6-$TARGETARCH.tar.xz -C /opt/Qt6
COPY build-$VERSION-slim/Qt6-$TARGETARCH-config.summary /opt/Qt6/config.summary
RUN rm /import/Qt6-$TARGETARCH.tar.xz

RUN echo "/opt/Qt6/lib" >> /etc/ld.so.conf && ldconfig
RUN echo "/usr/local/lib" >> /etc/ld.so.conf && ldconfig
ENV PATH="${PATH}:/opt/Qt6"
ENV QT_DIR="/opt/Qt6"
ENV QT_PLUGIN_PATH="/opt/Qt6/plugins"

# Set the default display server for Raspberry Pi. Use "wayland" if there is a need.
ENV QT_QPA_PLATFORM=eglfs

RUN apt-get -y autoremove \
	&& apt-get -y autoclean \
	&& apt-get -y clean \
	&& rm -rf /var/lib/apt/lists/*
